print("welcome to my world")
print("hello guys")
print("how are you today")
print("we will learn about python")
print("are you ready to learn about python")
print("a top-level programming language created by Guido van Rossum.")
print("open python online in a browser")
print("make a sentence about python")
print("happy working")
print("that's all from me thank you")